# Generated by Django 2.1.1 on 2018-11-22 23:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.TextField(default='')),
                ('dateNtime', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=22)),
                ('was_there', models.BooleanField(default=False)),
                ('youtube_url', models.URLField(default='')),
                ('attachment', models.FileField(default='', upload_to='uploaded_files')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolina.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
