# Generated by Django 2.0.2 on 2018-04-13 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=14, default=Decimal('0'), max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=14, default=Decimal('0'), max_digits=16)),
                ('dateNtime', models.DateTimeField(auto_now_add=True)),
                ('youtube_url', models.URLField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=14, default=Decimal('0'), max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=14, default=Decimal('0'), max_digits=16)),
                ('dateNtime', models.DateTimeField(auto_now_add=True)),
                ('youtube_url', models.URLField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
