# Generated by Django 2.1.1 on 2018-11-22 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='idd',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
