# Generated by Django 2.0.2 on 2018-04-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='searchqueries',
            old_name='text',
            new_name='body',
        ),
    ]
