# Generated by Django 2.1.1 on 2018-09-18 20:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0002_auto_20180414_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='searchqueries',
            name='latitude',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=22),
        ),
        migrations.AlterField(
            model_name='searchqueries',
            name='longitude',
            field=models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=22),
        ),
    ]
