# Generated by Django 2.1.1 on 2018-11-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0002_post_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='idd',
        ),
    ]
