# Generated by Django 2.1.1 on 2018-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0006_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchQueries',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='uploaded_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='', upload_to='uploaded_videos'),
        ),
    ]
