# Generated by Django 2.1.1 on 2018-11-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0009_post_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file_url',
        ),
    ]
