# Generated by Django 2.1.1 on 2018-11-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0010_auto_20181102_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
