# Generated by Django 2.1.1 on 2018-11-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0011_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
