# Generated by Django 2.1.1 on 2018-11-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolina', '0012_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='was_there',
            field=models.BooleanField(default=False),
        ),
    ]
